apiVersion: apps/v1
kind: Deployment

metadata:
  name: aiops-assistant

spec:
  replicas: 3

  selector:
    matchLabels:
      app: aiops-assistant

  template:
    metadata:
      labels:
        app: aiops-assistant

    spec:
      containers:
      - name: aiops-assistant

        image: aiops-assistant:latest

        imagePullPolicy: Never

        ports:
        - containerPort: 8501

        resources: 
          requests:
            cpu: "100m"
            memory": "128mi"

          limits:
            cpu: "500m"
            memory: "512mi"

